### ISSUE TITLE
Clarify using a code example?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-zawrs#11]
Could you please clarify how these instructions work by including a small example code fragment? I'm confused by the implications of the comment:

> These instructions are not supported in a constrained LR/SC loop.

Can you explain this further?

Thanks.

**Comment by adurbin-rivos** [comment]
I believe the intention is that one cannot use wrs instruction within LR/SC loop because the LR is already taking a reservation. The ISA spec currently has the following:

> An SC may succeed only if no store from another hart to the reservation set can be observed to have occurred between the LR and the SC, and if there is no other SC between the LR and itself in program order. An SC may succeed only if no write from a device other than a hart to the bytes accessed by the LR instruction can be observed to have occurred between the LR and SC.


Given that, the addition of wrs doesn't necessarily complicate a design while allowing wrs within an LR/SC loop would need additional changes.  I can't think of a reason why someone would want to put a wrs instruction within such a loop because the next SC would inherently fail if wrs was on the same reservation set as the SC. If it was a different reservation set I think that situation falls into "no other SC between the LR and itself in program order" since wrs is effectively taking a reservation.

**Comment by JamesKenneyImperas** [comment]
Ok, I see what you are saying: `LR` can be used _either_ in combination with `SC` _or_ in combination with `WRS.*`, but not both at the same time. So an example use might be something like:

```
    la    t0, lock_address
    sw    zero,(t0)    // clear lock
1:  lr.w  t1,(t0)      // establish reservation
    bnez  t1, 1f       // done if lock written
    wrs.sto            // wait for a possible write to the lock
    lw    t1,(t0)      // get written value
    beqz  t1, 1b       // repeat if not yet written
1:
```

Is that the right kind of thing?

**Comment by adurbin-rivos** [comment]
That would be my understanding, yes.  Likewise, a similar construction could be used for signalling threads -- not necessarily using lock paradigms. i.e. think of a tight polling thread. wrs could be used to poll while not burning power to achieve the lowest latency of being signaled.
